#!/usr/bin/env bun
/**
 * gen-prereqs.ts — emit the README "Prerequisites" block.
 *
 * Usage:
 *   bun scripts/gen-prereqs.ts          # print markdown to stdout
 *   bun scripts/gen-prereqs.ts --check  # exit 1 if README drift detected
 *
 * Single source of truth: the PER_AGENT_CLIS table below. When the per-agent
 * CLI list changes, update this table and re-run.
 */
import { readFile } from "node:fs/promises"
import { resolve } from "node:path"

const ROOT = resolve(import.meta.dir, "..")
const README = resolve(ROOT, "README.md")

const BEGIN_MARKER = "<!-- BEGIN: gen-prereqs -->"
const END_MARKER = "<!-- END: gen-prereqs -->"

type AgentCli = { agent: string; clis: string[]; note?: string }

const PER_AGENT_CLIS: AgentCli[] = [
  { agent: "backend-developer", clis: ["bun", "bunx", "uv", "uvx", "curl", "jq"] },
  { agent: "frontend-developer", clis: ["bun", "bunx", "vite", "playwright"] },
  { agent: "database-admin", clis: ["psql", "sqlite3", "drizzle-kit / prisma"] },
  { agent: "devops-engineer", clis: ["docker", "docker-compose", "kubectl", "helm", "gh"] },
  { agent: "cloud-architect", clis: ["terraform", "aws", "gcloud", "az"] },
  { agent: "qa-tester", clis: ["playwright", "vitest", "bun test", "pytest"] },
  { agent: "security-analyst", clis: ["bunx varlock", "trivy", "semgrep", "gitleaks"] },
  { agent: "pentester", clis: ["nmap", "nikto", "ffuf"], note: "authorised testing only" },
  { agent: "ml-engineer", clis: ["uv", "python", "jupyter"] },
  { agent: "ui-ux-designer", clis: [], note: "no Bash — no CLI deps" },
  { agent: "github-manager", clis: ["gh", "git"] },
  { agent: "product-manager", clis: [], note: "no Bash — no CLI deps" },
  { agent: "agent-builder", clis: ["bun", "bunx"] },
  { agent: "system-architect", clis: [], note: "no Bash — no CLI deps" },
]

const PACKAGE_MANAGER_PREFS = [
  "**Node ecosystem** → `bun` / `bunx` (never `npm`, `npx`, `yarn`, `pnpm`).",
  "**Python ecosystem** → `uv` / `uvx` (never `pip`, `pipx`, `poetry`).",
  "**JSON reading** → `jq` (never `python3 -c 'import json...'`).",
]

function renderBlock(): string {
  const lines: string[] = []
  lines.push(BEGIN_MARKER)
  lines.push("")
  lines.push("## Prerequisites")
  lines.push("")
  lines.push(
    "Agents are Bash-enabled but do not install CLIs themselves. Install the ones the agents you use actually need — no global install required for the plugin itself.",
  )
  lines.push("")
  lines.push("### Per-agent CLIs")
  lines.push("")
  lines.push("| Agent | CLIs |")
  lines.push("|---|---|")
  for (const { agent, clis, note } of PER_AGENT_CLIS) {
    const body =
      clis.length > 0
        ? clis.map((c) => `\`${c}\``).join(", ") + (note ? ` *(${note})*` : "")
        : note
          ? `*${note}*`
          : "—"
    lines.push(`| \`${agent}\` | ${body} |`)
  }
  lines.push("")
  lines.push("### Package-manager preferences")
  lines.push("")
  for (const pref of PACKAGE_MANAGER_PREFS) {
    lines.push(`- ${pref}`)
  }
  lines.push("")
  lines.push(
    "_This section is generated by `scripts/gen-prereqs.ts`. Edit the script's `PER_AGENT_CLIS` table and re-run to update._",
  )
  lines.push("")
  lines.push(END_MARKER)
  return lines.join("\n")
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check")
  const block = renderBlock()

  if (!check) {
    process.stdout.write(`${block}\n`)
    return
  }

  // Drift check: confirm README between markers matches rendered block exactly.
  const readme = await readFile(README, "utf8")
  const beginIdx = readme.indexOf(BEGIN_MARKER)
  const endIdx = readme.indexOf(END_MARKER)
  if (beginIdx === -1 || endIdx === -1) {
    console.error(
      `[gen-prereqs] README.md missing markers. Insert ${BEGIN_MARKER} … ${END_MARKER} around the Prerequisites section.`,
    )
    process.exit(1)
  }
  const current = readme.slice(beginIdx, endIdx + END_MARKER.length)
  if (current !== block) {
    console.error(
      "[gen-prereqs] README.md Prerequisites block drifted from gen-prereqs.ts. Re-run without --check and paste the output between the markers.",
    )
    process.exit(1)
  }
  console.log("[gen-prereqs] README.md Prerequisites block in sync.")
}

await main()
